define Device/AX3000_1600_VDSL35B_SEC_DEBUG
  $(Device/xrx500)
  DEVICE_DTS := easy350_anywan_axepoint
  DEVICE_TITLE := AX3000 1600 VDSL35B Debug Secure Gateway
  FAKED_ENV := $(FAKEROOT_PROG)
  ROOTFS_PREPARE := add-servicelayer-schema
  DEVICE_PACKAGES := $(UGW_PACKAGES_SEC) $(UGW_PACKAGES_SEC_DEBUG) \
                     $(VOIP_PACKAGES_SLIC200_MAIN) $(DECT_PACKAGES_SEC) $(DECT_PACKAGES_SEC_DEBUG) \
                     $(DSL_CPE_UGW_PACKAGE) $(DSL_CPE_PACKAGES_R5) $(DSL_CPE_PACKAGES_DEBUG) \
                     $(AX_PACKAGES) $(REPEATER_PACKAGES) $(GUEST_ACCESS_PACKAGES)
endef
TARGET_DEVICES += AX3000_1600_VDSL35B_SEC_DEBUG

define Device/AX6000_2000_VDSL35B_SEC_DEBUG
  $(Device/AX3000_1600_VDSL35B_SEC_DEBUG)
  DEVICE_DTS := easy550_anywan_axepoint
  DEVICE_TITLE := AX6000 2000 VDSL35B Debug Secure Gateway
endef
TARGET_DEVICES += AX6000_2000_VDSL35B_SEC_DEBUG
